name: threads
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.3.1
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
flutter:
  uses-material-design: true

  assets:
    - assets/
